import os
from psycopg_pool import AsyncConnectionPool


def create_pool(database_url):
    pool = AsyncConnectionPool(conninfo=database_url,open=False)
    return pool

async def database_init(pool):
    """ Initialize connection """
    async with pool.connection() as conn:
      await conn.execute("""
        CREATE TABLE IF NOT EXISTS tasks(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        done BOOLEAN NOT NULL DEFAULT False
        )
        """)
      await conn.execute(""" 
      INSERT INTO tasks (title,done)
      SELECT title,done
      FROM ( 
          VALUES 
          ('study',TRUE),
          ('work',FALSE),
          ('clean',TRUE) 
      ) AS seed(title, done)
      WHERE NOT EXISTS (SELECT 1 FROM tasks)
      """)





